research_task:
  description: >
    Conduct a deep research about {topic}
    Make sure you find any interesting, relevant and update information given
    the current year of 2025. You can use free APIs, web pages and jurisprudences to get most update informations if needed.
  expected_output: >
    A list with 10 most relevant and update laws launched in the last 7 days in the {topic}
  agent: juris_researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report in Portugues-BR with the main topics and it's details, each with a full section of information.
    Present the result with sections showing each law and it's description when possible.
    Formatted as markdown without '```'
  agent: reporting_analyst
